name: Markdown File Governance

on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  check-md-locations:
    name: Validate Markdown File Locations
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Markdown file governance
        run: |
          echo "🔍 Checking Markdown file locations against governance rules..."
          echo ""
          
          # Find .md files in forbidden locations
          FORBIDDEN_MD=$(find . -name "*.md" \
            -not -path "./README.md" \
            -not -path "./CLAUDE.md" \
            -not -path "./.claude/*" \
            -not -path "./docs/*" \
            -not -path "./test-results/*" \
            -not -path "./playwright-report/*" \
            -not -path "./node_modules/*" \
            -not -path "./.next/*" \
            -not -path "./.git/*" \
            2>/dev/null || true)
          
          if [ ! -z "$FORBIDDEN_MD" ]; then
            echo "❌ ERROR: Markdown files found in forbidden locations:"
            echo ""
            echo "$FORBIDDEN_MD"
            echo ""
            echo "📋 Approved locations (see docs/MARKDOWN-FILE-GOVERNANCE.md):"
            echo "  - Root: README.md, CLAUDE.md only"
            echo "  - Agent config: ./.claude/agents/*.md"
            echo "  - Operational guides: ./docs/*.md"
            echo "  - Planning/Audit: ./docs/md-files/*.md"
            echo ""
            echo "💡 Please move files to approved locations before merging."
            exit 1
          fi
          
          echo "✅ All Markdown files are in approved locations"
          
      - name: Validate with governance script
        run: |
          if [ -f "scripts/check-md-governance.sh" ]; then
            echo ""
            echo "🔍 Running governance validation script..."
            bash scripts/check-md-governance.sh
          fi
